import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import HomeBanner from "../components/HomeBanner";
import Style from "../CSSfile/StartingPage.module.css";
import SportsTerms from "../components/SportsTerms";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [pressedUserId, setPressedUserId] = useState("");
  console.log(pressedUserId);
  return (
    <>
      <Head>
        <title>Employee Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-3">
        <div
          style={{
            backgroundImage: `url('https://img.freepik.com/free-vector/people-celebrating-together-illustration-theme_23-2148409129.jpg?size=626&ext=jpg&ga=GA1.2.190334821.1684960559&semt=ais')`,
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover"
          }}
          className={`min-h-screen`}
        >
          <div className="flex justify-center">
            <HomeBanner></HomeBanner>
          </div>
          <div>
            <SportsTerms></SportsTerms>
          </div>
        </div>
        <div className="flex justify-center mb-8">
          
        </div>
      </main>
    </>
  );
}
